#!/bin/bash

GNUCAP_TESTFILTER=cat

[ x$1 = xSKIP ] && exit 77

base=`basename $1`
out=${base}.out
ref=${1}.ref
make $out
# diff $out $ref
$GNUCAP_TESTFILTER $out < $ref | diff -up - $ref --label $ref || exit 1
rm $out
